-- INSERT IGNORE INTO weblog.users (`id`, `username`, `password`) VALUES ('1', 'user', '$2a$11$IYiD4i.CUO8WLYryFx/ghuMoavc1vcGFfYvNOT.i7bR2V9LZGDIUm');
-- INSERT IGNORE INTO weblog.authorities (`id`, `username`, `authority`) VALUES ('1', 'user', 'user');
