/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QRZClient2;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Library {
	static Logger logger = LoggerFactory.getLogger("Library");
	
    public static void main(String[] args) {
    	logger.info("Info");
    	logger.error("Error");
    	logger.debug("Debug");
    	
    	QRZClient2 client = new QRZClient2();
    	try {
    		logger.info(client.lookupCallsign("2E1HNK").toString());
    		logger.info(client.lookupCallsign("G3MXH").toString());
    	} catch (QRZCallsignNotFoundException e) {
			e.printStackTrace();
		}
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
